---

networks:
  test:

services:
  app:
    build:
      context: app
    expose:
      - 80
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_DB: test
    networks:
      - test
    depends_on:
      - db
  db:
    image: mongo:4
    expose:
      - 27017
  test:
    build:
      context: test
    environment:
      ENDPOINT: http://app
    networks:
      - test
    depends_on:
      - app
