name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t api-ci:${{ github.run_number }} app
    - name: Build tests Docker image
      run: docker build -t api-ci-test:${{ github.run_number }} test
    - name: Create docker network
      run: docker network create test
    - name: Start application
      run: docker run -d --network test --name api-ci-run -e MONGO_HOST=db -e MONGO_PORT=27017 -e MONGO_DB=test -p 8080:80 api-ci:${{ github.run_number }}
    - name: Execute tests
      run: docker run --network test --rm --name api-ci-test -e ENDPOINT=http://api-ci-run api-ci-test:${{ github.run_number }}
    - name: Scan image
      uses: anchore/scan-action@v2
      with:
        image: api-ci:${{ github.run_number }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image
      run: |
        docker tag api-ci:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/api-ci:${{ github.run_number }}
        docker push luismiguelsaez/api-ci:${{ github.run_number }}